# ----------- CONFIGURABLE START -----------
title:            "IWDPA"
description:      "Independent Writing Departments and Programs Association"
url:              http://independentwriting.org # Site url, without a slash at the end.
signoff:          "IWDPA" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Home
    url:          /
    external:     false
  - name:         About 
    url:          /about
    external:     false
  - name:         History
    url:          /history
    external:     false 
  - name:         Bibliography
    url:          /bib
    external:     false
  - name:         Directory
    url:          /dir
    external:     false
  - name:         Contact Us
    url:          /contact
    external:     false 
    
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"